--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADM_ROLE_INFO
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."ADM_ROLE_INFO" 
   (	"ROLE_ID" VARCHAR2(20 BYTE), 
	"ROLE_DESC" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##SCOTT"."ADM_ROLE_INFO"."ROLE_ID" IS '권한 그룹 아이디';
   COMMENT ON COLUMN "C##SCOTT"."ADM_ROLE_INFO"."ROLE_DESC" IS '권한 그룹 설명';
REM INSERTING into C##SCOTT.ADM_ROLE_INFO
SET DEFINE OFF;
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_005','006');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_006','TEST 006');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_011','TEST_011');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_001','333');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_002','111');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_014','014');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_007','007');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_008','008');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_012','TEST 012');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_009','009');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_003','TEST 003');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_000','111');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_004','TEST_004');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_013','TEST 013');
Insert into C##SCOTT.ADM_ROLE_INFO (ROLE_ID,ROLE_DESC) values ('TEST_010','TEST_010');
--------------------------------------------------------
--  DDL for Index SYS_C007307
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SYS_C007307" ON "C##SCOTT"."ADM_ROLE_INFO" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADM_ROLE_INFO
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."ADM_ROLE_INFO" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."ADM_ROLE_INFO" ADD PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
