--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADM_GROUP_INFO
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."ADM_GROUP_INFO" 
   (	"GROUP_ID" VARCHAR2(20 BYTE), 
	"GROUP_DESC" VARCHAR2(60 BYTE), 
	"ROLE_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##SCOTT"."ADM_GROUP_INFO"."GROUP_ID" IS '사용자 그룹 아이디';
   COMMENT ON COLUMN "C##SCOTT"."ADM_GROUP_INFO"."GROUP_DESC" IS '사용자 그룹 설명';
   COMMENT ON COLUMN "C##SCOTT"."ADM_GROUP_INFO"."ROLE_ID" IS '권한 그룹 아이디';
REM INSERTING into C##SCOTT.ADM_GROUP_INFO
SET DEFINE OFF;
Insert into C##SCOTT.ADM_GROUP_INFO (GROUP_ID,GROUP_DESC,ROLE_ID) values ('USER_GROUP_005','USER_GROUP_005','TEST_005');
Insert into C##SCOTT.ADM_GROUP_INFO (GROUP_ID,GROUP_DESC,ROLE_ID) values ('USER_GROUP_006','USER_GROUP_006','TEST_006');
Insert into C##SCOTT.ADM_GROUP_INFO (GROUP_ID,GROUP_DESC,ROLE_ID) values ('USER_GROUP_004','USER_GROUP_004','TEST_004');
Insert into C##SCOTT.ADM_GROUP_INFO (GROUP_ID,GROUP_DESC,ROLE_ID) values ('USER_GROUP_007','USER_GROUP_007','TEST_007');
Insert into C##SCOTT.ADM_GROUP_INFO (GROUP_ID,GROUP_DESC,ROLE_ID) values ('USER_GROUP_003','003','TEST_001');
Insert into C##SCOTT.ADM_GROUP_INFO (GROUP_ID,GROUP_DESC,ROLE_ID) values ('USER_GROUP_001','222','TEST_005');
Insert into C##SCOTT.ADM_GROUP_INFO (GROUP_ID,GROUP_DESC,ROLE_ID) values ('USER_GROUP_002','USER_GROUP_002','TEST_002');
Insert into C##SCOTT.ADM_GROUP_INFO (GROUP_ID,GROUP_DESC,ROLE_ID) values ('ADMIN','관리자 그룹','TEST_001');
--------------------------------------------------------
--  DDL for Index SYS_C007305
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SYS_C007305" ON "C##SCOTT"."ADM_GROUP_INFO" ("GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADM_GROUP_INFO
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."ADM_GROUP_INFO" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."ADM_GROUP_INFO" ADD PRIMARY KEY ("GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
