--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADM_USER_INFO
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."ADM_USER_INFO" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"LANGUAGE_TYPE" VARCHAR2(10 BYTE), 
	"DEPARTMENT" VARCHAR2(20 BYTE), 
	"TOKEN" VARCHAR2(40 BYTE), 
	"USER_GROUP_ID" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(20 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(20 BYTE), 
	"USE_YN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."USER_ID" IS '사용자 아이디';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."USER_NAME" IS '사용자 이름';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."PASSWORD" IS '사용자 패스워드';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."LANGUAGE_TYPE" IS '사용 언어';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."DEPARTMENT" IS '부서 정보';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."TOKEN" IS '엑세스 토큰';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."USER_GROUP_ID" IS '사용자 그룹 아이디';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."CREATE_DATE" IS '생성 일시';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."CREATE_USER" IS '생성 사용자';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."UPDATE_DATE" IS '수정 일시';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."UPDATE_USER" IS '수정 사용자';
   COMMENT ON COLUMN "C##SCOTT"."ADM_USER_INFO"."USE_YN" IS '사용 구분';
REM INSERTING into C##SCOTT.ADM_USER_INFO
SET DEFINE OFF;
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('IBS','IBS','IBS','KO','SI',null,'USER_GROUP_003',null,null,to_date('21/04/01','RR/MM/DD'),'IBS',to_date('21/04/28','RR/MM/DD'),'DJCHOI','Y');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('TEST4','테스트4','1111','EN',null,null,'USER_GROUP_003',null,'000',to_date('21/04/29','RR/MM/DD'),'DJCHOI',to_date('21/04/30','RR/MM/DD'),'DJCHOI','N');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('IBS2','IBS2','IBS2','KO','SI','IBS2:20210427162405',null,null,null,to_date('21/04/01','RR/MM/DD'),'IBS',null,null,'Y');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('ABC','ABC','ABC','EN','SI',null,'USER_GROUP_002',null,null,to_date('21/04/30','RR/MM/DD'),'IBS',null,null,'Y');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('TEST2','테스트2','1111','CN',null,null,'USER_GROUP_003',null,'0000',to_date('21/04/29','RR/MM/DD'),'DJCHOI',to_date('21/04/29','RR/MM/DD'),'DJCHOI','Y');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('TEST3','테스트3','111','KO',null,null,'USER_GROUP_001',null,null,to_date('21/04/29','RR/MM/DD'),'DJCHOI',null,null,'N');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('GUEST','GUEST','GUEST','KO',null,'GUEST:20210518150147','USER_GROUP_002',null,null,to_date('21/04/30','RR/MM/DD'),'IBS',null,null,'Y');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('USER_001','Dog','Dog123','KO','Sales',null,'USER_GROUP_001',null,null,to_date('21/04/01','RR/MM/DD'),'IBS',null,null,'Y');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('USER_002','Cat','Cat123','EN','Logistics',null,'USER_GROUP_003',null,null,to_date('21/04/01','RR/MM/DD'),'IBS',to_date('21/04/28','RR/MM/DD'),'IBS','Y');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('USER_003','Bee','Bee123','CN','Marketing',null,'GROUP_003',null,null,to_date('21/04/01','RR/MM/DD'),'IBS',null,null,'Y');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('DJCHOI','최대진','1','KO','SI','DJCHOI:20210525095412','ADMIN','aaa@bbb.ccc','010-4752-9473',to_date('21/04/01','RR/MM/DD'),'IBS',to_date('21/04/28','RR/MM/DD'),'DJCHOI','Y');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('TEST1','테스트1','1111','EN',null,null,'USER_GROUP_004','aaa@misd.com','222',to_date('21/04/28','RR/MM/DD'),'DJCHOI',to_date('21/05/03','RR/MM/DD'),'DJCHOI','N');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('TEST5','테스트5','1111','KO',null,null,'USER_GROUP_003',null,null,to_date('21/04/30','RR/MM/DD'),'DJCHOI',null,null,'N');
Insert into C##SCOTT.ADM_USER_INFO (USER_ID,USER_NAME,PASSWORD,LANGUAGE_TYPE,DEPARTMENT,TOKEN,USER_GROUP_ID,EMAIL,PHONE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,USE_YN) values ('TESTEEE','wewe','111','KO',null,null,'USER_GROUP_002','ewe@aaaaaa.com',null,to_date('21/05/03','RR/MM/DD'),'DJCHOI',null,null,'Y');
--------------------------------------------------------
--  DDL for Index ADM_USER_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."ADM_USER_INFO_PK" ON "C##SCOTT"."ADM_USER_INFO" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADM_USER_INFO
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."ADM_USER_INFO" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."ADM_USER_INFO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."ADM_USER_INFO" ADD CONSTRAINT "ADM_USER_INFO_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SCOTT"."ADM_USER_INFO" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."ADM_USER_INFO" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."ADM_USER_INFO" MODIFY ("CREATE_USER" NOT NULL ENABLE);
