--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SYS_MENU_STRUCTURE
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."SYS_MENU_STRUCTURE" 
   (	"STRUCTURE_ID" VARCHAR2(20 BYTE), 
	"ROLE_GROUP_ID" VARCHAR2(20 BYTE), 
	"MENU_NAME" VARCHAR2(30 BYTE), 
	"HAS_CHILD" CHAR(1 BYTE) DEFAULT 'N', 
	"PARENT_KEY" VARCHAR2(20 BYTE), 
	"MENU_ID" VARCHAR2(20 BYTE), 
	"SYSTEM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##SCOTT.SYS_MENU_STRUCTURE
SET DEFINE OFF;
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('01','TEST_001','SYSTEM','Y',null,null,'ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('01-01','TEST_001','권한 관리','N','01','M0001','ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('01-02','TEST_001','사용자 그룹 관리','N','01','M0002','ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('01-03','TEST_001','사용자 관리','N','01','M0003','ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('01-05','TEST_001','로그 아웃','N','01','M0004','ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('02','TEST_001','INQUIRY','Y',null,null,'ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('02-01','TEST_001','서브 메뉴','Y','02',null,'ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('02-01-01','TEST_001','INQUIRY 1','N','02-01','M0021','ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('02-01-02','TEST_001','INQUIRY 2','N','02-01','M0022','ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('02-02','TEST_001','TEST TEST ','N','02','M0103','ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('03','TEST_001','TEST MENU 1','Y',null,null,'ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('03-01','TEST_001','TEST SUB MENU 1','N','03','M0101','ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('03-02','TEST_001','TEST SUB MENU GROUP 1','Y','03',null,'ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('03-02-01','TEST_001','TEST SUB MENU GROUP MENU 1','N','03-02','M0102','ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('01-04','TEST_001','시스템코드 관리','N','01','M0021','ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('02-01-03-01','TEST_001','서브 메뉴 2 서브 메뉴','N','02-01-03','M0100','ADMIN');
Insert into C##SCOTT.SYS_MENU_STRUCTURE (STRUCTURE_ID,ROLE_GROUP_ID,MENU_NAME,HAS_CHILD,PARENT_KEY,MENU_ID,SYSTEM) values ('02-01-03','TEST_001','서브 메뉴 그룹 3','Y','02-01',null,'ADMIN');
--------------------------------------------------------
--  DDL for Index SYS_C007798
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SYS_C007798" ON "C##SCOTT"."SYS_MENU_STRUCTURE" ("STRUCTURE_ID", "ROLE_GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SYS_MENU_STRUCTURE
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."SYS_MENU_STRUCTURE" MODIFY ("STRUCTURE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."SYS_MENU_STRUCTURE" MODIFY ("ROLE_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."SYS_MENU_STRUCTURE" ADD PRIMARY KEY ("STRUCTURE_ID", "ROLE_GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
