--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SYS_SYSTEM_CODE_DATA
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."SYS_SYSTEM_CODE_DATA" 
   (	"TABLE_NAME" VARCHAR2(30 BYTE), 
	"CODE_NAME" VARCHAR2(30 BYTE), 
	"CODE_SEQ" NUMBER(4,0), 
	"CODE_DESC" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##SCOTT.SYS_SYSTEM_CODE_DATA
SET DEFINE OFF;
Insert into C##SCOTT.SYS_SYSTEM_CODE_DATA (TABLE_NAME,CODE_NAME,CODE_SEQ,CODE_DESC) values ('MULTI_LANG_CD','EN',2,'영어');
Insert into C##SCOTT.SYS_SYSTEM_CODE_DATA (TABLE_NAME,CODE_NAME,CODE_SEQ,CODE_DESC) values ('MULTI_LANG_CD','CN',3,'중국어');
Insert into C##SCOTT.SYS_SYSTEM_CODE_DATA (TABLE_NAME,CODE_NAME,CODE_SEQ,CODE_DESC) values ('MULTI_LANG_CD','KR',1,'한국어');
Insert into C##SCOTT.SYS_SYSTEM_CODE_DATA (TABLE_NAME,CODE_NAME,CODE_SEQ,CODE_DESC) values ('FLAG_YN','Y',1,'예');
Insert into C##SCOTT.SYS_SYSTEM_CODE_DATA (TABLE_NAME,CODE_NAME,CODE_SEQ,CODE_DESC) values ('FLAG_YN','N',2,'아니오');
Insert into C##SCOTT.SYS_SYSTEM_CODE_DATA (TABLE_NAME,CODE_NAME,CODE_SEQ,CODE_DESC) values ('USE_YN','Y',1,'사용');
Insert into C##SCOTT.SYS_SYSTEM_CODE_DATA (TABLE_NAME,CODE_NAME,CODE_SEQ,CODE_DESC) values ('USE_YN','N',2,'미사용');
Insert into C##SCOTT.SYS_SYSTEM_CODE_DATA (TABLE_NAME,CODE_NAME,CODE_SEQ,CODE_DESC) values ('DEPARTMENT','SI',1,'SI사업부');
Insert into C##SCOTT.SYS_SYSTEM_CODE_DATA (TABLE_NAME,CODE_NAME,CODE_SEQ,CODE_DESC) values ('DEPARTMENT','SOLUTION',2,'솔루션사업부');
Insert into C##SCOTT.SYS_SYSTEM_CODE_DATA (TABLE_NAME,CODE_NAME,CODE_SEQ,CODE_DESC) values ('DEPARTMENT','MANAGEMENT',3,'경영지원팀');
--------------------------------------------------------
--  DDL for Index SYS_C0010412
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SYS_C0010412" ON "C##SCOTT"."SYS_SYSTEM_CODE_DATA" ("TABLE_NAME", "CODE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SYS_SYSTEM_CODE_DATA
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."SYS_SYSTEM_CODE_DATA" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."SYS_SYSTEM_CODE_DATA" MODIFY ("CODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."SYS_SYSTEM_CODE_DATA" ADD CONSTRAINT "SYS_C0010412" PRIMARY KEY ("TABLE_NAME", "CODE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
