--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SYS_MENU_INFO
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."SYS_MENU_INFO" 
   (	"MENU_ID" VARCHAR2(20 BYTE), 
	"MENU_NAME" VARCHAR2(30 BYTE), 
	"MENU_DESC" VARCHAR2(200 BYTE), 
	"SYS_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##SCOTT.SYS_MENU_INFO
SET DEFINE OFF;
Insert into C##SCOTT.SYS_MENU_INFO (MENU_ID,MENU_NAME,MENU_DESC,SYS_ID) values ('M0001','권한 관리','권한 관리 메뉴','ADMIN');
Insert into C##SCOTT.SYS_MENU_INFO (MENU_ID,MENU_NAME,MENU_DESC,SYS_ID) values ('M0002','사용자 그룹 관리','사용자 그룹 관리 메뉴','ADMIN');
Insert into C##SCOTT.SYS_MENU_INFO (MENU_ID,MENU_NAME,MENU_DESC,SYS_ID) values ('M0003','사용자 관리','사용자 관리 메뉴','ADMIN');
Insert into C##SCOTT.SYS_MENU_INFO (MENU_ID,MENU_NAME,MENU_DESC,SYS_ID) values ('M0004','로그 아웃','로그 아웃','ADMIN');
Insert into C##SCOTT.SYS_MENU_INFO (MENU_ID,MENU_NAME,MENU_DESC,SYS_ID) values ('M0021','서브 메뉴 1','서브 메뉴 1','ADMIN');
Insert into C##SCOTT.SYS_MENU_INFO (MENU_ID,MENU_NAME,MENU_DESC,SYS_ID) values ('M0022','서브 메뉴 2','서브 메뉴 2','ADMIN');
Insert into C##SCOTT.SYS_MENU_INFO (MENU_ID,MENU_NAME,MENU_DESC,SYS_ID) values ('M0023','INQUIRY1','INQUIRY1','ADMIN');
--------------------------------------------------------
--  DDL for Index SYS_C007800
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SYS_C007800" ON "C##SCOTT"."SYS_MENU_INFO" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SYS_MENU_INFO
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."SYS_MENU_INFO" MODIFY ("MENU_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."SYS_MENU_INFO" ADD PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
